### ISSUE TITLE
Is there any option to use it with non preset projects?

### ISSUE THREAD

**Issue by purbon** [atlanmod/busfactor_demo#1]
Good morning,
    I'm interested on running this bus factor analysis with other open source project, would be a very interesting exercise. But during my first look i found that you are really providing a set of, might be preprocessed, files for each projects.

Could you document how to get another project into busfactor?, if possible it would be very nice.

**Comment by valeriocos** [comment]
Hello,
the process to generate the files is not available at the moment (but it will be in a couple of weeks), however if you want, I can calculate bus factor for your repository/ies and send you back the result

cheers

**Comment by purbon** [comment]
@valeriocos would love to do it myself, feel free to keep me up to date when this is open, so I can test with other repos  :+1: 

But I guess, you can probably release some scripts that can create this files for now, right? or is there a lot of preprocessing involved? For me it does not need to be a very fancy thing, just a way to scrap some data and create this repos ;-)

Looking forward to it,
- purbon

**Comment by valeriocos** [comment]
I'll let you know as soon as I push the code. The process is a bit more complex and the bus factor is just a possible outcome of the tool we used to calculate it (https://github.com/valeriocos/Gitana)

**Comment by purbon** [comment]
Awesome @valeriocos, looking forward to play with it more in deep!! :+1:

**Comment by valeriocos** [comment]
@purbon, now you can run the bus factor on your repository, just check https://github.com/valeriocos/BusFactor.

**Comment by purbon** [comment]
Thanks a lot! I will keep you posted if I find any bug when I run this. Greetings to @jcabot ;-)
